# Generated by Django 3.2.9 on 2022-05-17 09:25

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20220516_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
