# Generated by Django 2.0.8 on 2018-08-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_remove_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
