# Generated by Django 3.2.9 on 2022-05-19 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20220516_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
