# Generated by Django 3.2.9 on 2022-05-25 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0005_auto_20220524_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pending_friends',
            field=models.ManyToManyField(blank=True, related_name='pending_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
