# Generated by Django 2.0.8 on 2018-09-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20180901_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_text',
            field=models.TextField(),
        ),
    ]
