# Generated by Django 2.0.8 on 2018-09-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20180902_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_text',
            field=models.CharField(max_length=50000),
        ),
    ]
