# Generated by Django 3.2.9 on 2022-06-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='User',
            new_name='user',
        ),
    ]
