# Generated by Django 3.2 on 2022-06-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_rename_user_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
