# Generated by Django 3.2.13 on 2022-06-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='thumb_image',
            field=models.CharField(default='default_user.jpg', max_length=200),
        ),
    ]
